-- Mapping-Tabelle: E-Mail-Domain -> Stadt (deterministisch, nur eindeutige Faelle)
CREATE TABLE IF NOT EXISTS public.school_domain_city_map (
  domain text PRIMARY KEY,
  city   text NOT NULL,
  note   text
);

INSERT INTO public.school_domain_city_map (domain, city) VALUES
 ('stadt.wuppertal.de','Wuppertal'),
 ('stadt-duisburg.de','Duisburg'),
 ('ebw-duisburg.de','Duisburg'),
 ('duesseldorf.de','Düsseldorf'),
 ('schule.duesseldorf.de','Düsseldorf'),
 ('katholisches-duesseldorf.de','Düsseldorf'),
 ('schule.essen.de','Essen'),
 ('ggs-ess.de','Essen'),
 ('bielefeld.de','Bielefeld'),
 ('stieghorst.schule','Bielefeld'),
 ('gelsenkirchen.de','Gelsenkirchen'),
 ('caritas-gelsenkirchen.de','Gelsenkirchen'),
 ('stadt-koeln.de','Köln'),
 ('schulen-koeln.de','Köln'),
 ('schule.koeln','Köln'),
 ('stadtdo.de','Dortmund'),
 ('dortmund.de','Dortmund'),
 ('ekkdo.de','Dortmund'),
 ('muelheim-ruhr.de','Mülheim an der Ruhr'),
 ('schulen-bonn.de','Bonn'),
 ('bonn.de','Bonn'),
 ('remscheid.de','Remscheid'),
 ('stadt.leverkusen.de','Leverkusen'),
 ('herford.de','Herford'),
 ('mail.aachen.de','Aachen'),
 ('gerlachschule-aachen.de','Aachen'),
 ('schulengevelsberg.de','Gevelsberg'),
 ('solingen.de','Solingen'),
 ('wesseling.de','Wesseling'),
 ('lage.de','Lage'),
 ('paderborn.de','Paderborn'),
 ('stadt-emmerich.de','Emmerich am Rhein'),
 ('stadt.mainz.de','Mainz'),
 ('wilhelmshaven.de','Wilhelmshaven'),
 ('esslingen.de','Esslingen am Neckar'),
 ('oberhausen.de','Oberhausen'),
 ('bgs-ob.de','Oberhausen'),
 ('bad-duerkheim.de','Bad Dürkheim'),
 ('bad-lippspringe.de','Bad Lippspringe'),
 ('bad-zwischenahn.de','Bad Zwischenahn'),
 ('bergheim.de','Bergheim'),
 ('bernkastel-kues.de','Bernkastel-Kues'),
 ('bochum.de','Bochum'),
 ('bottrop.de','Bottrop'),
 ('braunschweig.de','Braunschweig'),
 ('christoph-kolumbus-gs.ingolstadt.de','Ingolstadt'),
 ('crs-dormagen.de','Dormagen'),
 ('eks-dormagen.de','Dormagen'),
 ('sbh-dormagen.de','Dormagen'),
 ('detmold.de','Detmold'),
 ('dinslaken.de','Dinslaken'),
 ('domschule-minden.de','Minden'),
 ('minden.de','Minden'),
 ('erich-kaestner-schule.ratingen.de','Ratingen'),
 ('falkschule-warburg.de','Warburg'),
 ('fesh-hagen.de','Hagen'),
 ('fks-schwerte.de','Schwerte'),
 ('geilenkirchen.de','Geilenkirchen'),
 ('ggs-adl-kleve.nrw.schule','Kleve'),
 ('montessorischule-kleve.eu','Kleve'),
 ('ggs-kranenburg.de','Kranenburg'),
 ('grbo.schulen-hamm.de','Hamm'),
 ('grmc.schulen-hamm.de','Hamm'),
 ('grsch.schulen-hamm.de','Hamm'),
 ('grst.schulen-hamm.de','Hamm'),
 ('hermann-gmeiner-schule-hamm.de','Hamm'),
 ('grevenbroich.de','Grevenbroich'),
 ('grundschule-wirges.de','Wirges'),
 ('gs-badkreuznach.de','Bad Kreuznach'),
 ('gs-bingen.de','Bingen am Rhein'),
 ('gs-cla.schulen-herne.de','Herne'),
 ('herne.de','Herne'),
 ('gs-koenigswinter.de','Königswinter'),
 ('gsfreiherrvomstein.bildung.koblenz.de','Koblenz'),
 ('pestalozzi-koblenz.de','Koblenz'),
 ('gsr.ronnenberg.de','Ronnenberg'),
 ('gswesendorf.de','Wesendorf'),
 ('herten.de','Herten'),
 ('karlschule-tuttlingen.de','Tuttlingen'),
 ('kornwestheim.de','Kornwestheim'),
 ('laatzen.de','Laatzen'),
 ('lambertischule.aurich.de','Aurich'),
 ('landau.de','Landau in der Pfalz'),
 ('ludgerusschule-rheine.de','Rheine'),
 ('michaelschule-rheine.de','Rheine'),
 ('luebbecke.de','Lübbecke'),
 ('mannheim.de','Mannheim'),
 ('marienschule-senden.de','Senden'),
 ('meerbusch.de','Meerbusch'),
 ('mittwaldschule-espelkamp.de','Espelkamp'),
 ('mls.schule.gronau.de','Gronau'),
 ('moers.de','Moers'),
 ('neuwied.de','Neuwied'),
 ('norder-schulen.de','Norden'),
 ('pgs-dueren.de','Düren'),
 ('plochingen.schule.bwl.de','Plochingen'),
 ('reutlingen.de','Reutlingen'),
 ('schramberg.de','Schramberg'),
 ('schule-witten.de','Witten'),
 ('schulen.krefeld.de','Krefeld'),
 ('schulen.langenfeld.de','Langenfeld'),
 ('schulstrasse-heiligenhaus.de','Heiligenhaus'),
 ('sonnenhofschule-pforzheim.de','Pforzheim'),
 ('stadt-gladbeck.de','Gladbeck'),
 ('stadt-muenster.de','Münster'),
 ('stadt-oldenburg.de','Oldenburg'),
 ('stuttgart.de','Stuttgart'),
 ('syke.de','Syke'),
 ('viersen.de','Viersen'),
 ('wesel.de','Wesel'),
 ('ass-wunstorf.de','Wunstorf'),
 ('mariannenschule.de','Werl'),
 ('rhein-erft-kreis.de','Bergheim')
ON CONFLICT (domain) DO NOTHING;

-- ── Post-Migration-Cleanup (ad-hoc via MCP nach dem Apply entfernt) ──
-- Zwei Domains wurden nach dieser Migration wieder gelöscht; Live-Stand = 111 Zeilen.
-- Hier nachgezogen, damit Repo == DB (drift-backfill). 0 Deals betroffen — die
-- Reihenfolge ggü. der Apply-Migration (…142116) ist daher ergebnisneutral.
DELETE FROM public.school_domain_city_map
WHERE domain IN ('rhein-erft-kreis.de','mariannenschule.de');
